---
apiVersion: v1
kind: Service
metadata:
  name: google-app-scheduler-svc
  labels:
    app: google-app-scheduler
spec:
  selector:
    app: google-app-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-app-scheduler-deployment
  labels:
    app: google-app-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-app-scheduler
  template:
    metadata:
      labels:
        app: google-app-scheduler
    spec:
      containers:
      - name: google-scheduler
        command: ["streamlit", "run", "src/app/main.py", "--server.port", "80", "--server.address", "0.0.0.0"]
        image: localhost:32000/scheduler-streamlit:v1
        ports:
        - containerPort: 8080